---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Download and Install Node source
  shell: |
    curl -sl https://deb.nodesource.com/setup_14.x | sudo -E bash -

- name: install nodejs and npm
  shell: |
    sudo apt-get install -y nodejs


- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present