---
- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: 'extract the tar/zipped file'
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/backend-app

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: "Executing Node with PM2"
  shell: |
    cd ~/backend-app/dist


    cd ../
    npm install

    npm run build

    sudo npm install forever -g
    sudo npm install ts-node -g
    forever start -c "ts-node -r tsconfig-paths/register -r dotenv/config src/main.ts" ./

  register: execute_node

- name: print message
  debug: 
    msg: "{{execute_node.stdout_lines}}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu